=== Lorenzo-Gandini/Fanta-Calcetto/XML/classifica.dtd
<!ELEMENT CLASSIFICA (CAMPIONATO)*>
<!ELEMENT CAMPIONATO (SQUADRA)*>
<!ELEMENT SQUADRA (PUNTI)>
<!ELEMENT PUNTI (#PCDATA)>

<!ATTLIST CLASSIFICA genere (Generale | Giornaliera) #REQUIRED>
<!ATTLIST CAMPIONATO nomeCampionato CDATA #REQUIRED>
<!ATTLIST CAMPIONATO giornata CDATA #IMPLIED>
<!ATTLIST SQUADRA nomeSquadra CDATA #REQUIRED>

=== Lorenzo-Gandini/Fanta-Calcetto/XML/classificaGenerale.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE CLASSIFICA SYSTEM "classifica.dtd">
<CLASSIFICA genere="Generale">
	<CAMPIONATO nomeCampionato="CampionatoGenerale">
		<SQUADRA nomeSquadra="suadraADmin">
			<PUNTI>28</PUNTI>
		</SQUADRA>
		<SQUADRA nomeSquadra="sqCTTT">
			<PUNTI>24</PUNTI>
		</SQUADRA>
		<SQUADRA nomeSquadra="Super">
			<PUNTI>0</PUNTI>
		</SQUADRA>
	</CAMPIONATO>
</CLASSIFICA>
